### ISSUE TITLE
Sensor conversion to physical switch

### ISSUE THREAD

**Issue by moesfeld** [klausahrenberg/WDoorSensor#5]
Im looking into converting this sensor from magnetic to physical switch. That switch will go into the bolt receiver of the door so it will send an mqtt when the door is locked/unlocked. Anyone with insights into the hardware can say if this can be done? From the Pictures I saw over at Tasmota Github it should be pretty straight forward just replacing the magnetic "bulb"?

Kind regards and thanks for this nice project

**Comment by klausahrenberg** [comment]
Yes, it's possible to unsolder the magnet contact and use a physical switch instead.
